strings = {
    'en': {
        # General
        'not_admin': "⛔ This command is for server admins only!",
        'select_category': "Select a category...",
        'choose_language': "Choose your language:",
        
        # Stats
        'stats_status': "Statistics: {guilds} Servers | {users} Users | Uptime: {uptime}",
        
        # AutoMod
        'automod_title': "🛡️ AutoMod Settings",
        'automod_description': "Configure automatic moderation features",
        'automod_enabled': "AutoMod Enabled",
        'automod_disabled': "AutoMod Disabled", 
        'anti_spam': "Anti-Spam",
        'anti_mention': "Anti-Mention",
        'anti_links': "Anti-Links",
        'bad_words': "Bad Words Filter",
        'automod_updated': "✅ AutoMod settings updated!",
        'automod_action': "🛡️ AutoMod Action",
        'spam_detection': "Spam Detection",
        'mass_mention': "Mass Mention",
        'link_posted': "Link Posted",
        'bad_word': "Bad Word",
        'automod_message_blocked': "🚫 Your message was blocked by AutoMod",
        'automod_spam_blocked': "⚠️ Please stop spamming!",
        'automod_mentions_blocked': "⚠️ Too many mentions!",
        'automod_links_blocked': "⚠️ Links are not allowed!",
        'automod_words_blocked': "⚠️ Inappropriate language detected!",
        
        # Language
        'language_set': "✅ Bot language set to English.",
        'language_set_ar': "✅ تم تعيين اللغة للعربية.",
        'english': "English 🇺🇸",
        'arabic': "Arabic 🇸🇦",
        
        # Help Menu
        'help_title': "🎯 Main Commands Menu",
        'help_description': "**Welcome to the help menu!**\n\nSelect a category from the dropdown below to explore available commands.\n\n• **🛡️ Protection** - Server security and moderation\n• **📋 General** - Everyday utility commands  \n• **⚙️ Admin** - Administrative tools (Admins only)\n• **ℹ️ Information** - Bot and developer info\n• **🎵 Music** - Buy Premium Version to use this Feature",
        'protection_commands': "🛡️ Protection Commands",
        'general_commands': "📋 General Commands", 
        'music_commands': "🎵 Music Commands",  # تم التصحيح هنا
        'admin_commands': "⚙️ Admin Commands",
        'info_commands': "ℹ️ Information",
        
        # Protection Commands
        'protection_title': "🛡️ Protection Commands",
        'protection_description': "**Server protection commands:**\n\n",
        'antibots_on': "Enable bot protection",
        'antibots_off': "Disable bot protection",
        'settings_view': "View protection settings",
        'current_settings': "Current Protection Settings",
        'available_settings': "Available Settings",
        'setting_usage': "Usage: `/settings <setting> <value>`",
        'logs_set': "✅ Logs channel set to {channel}",
        'logs_removed': "✅ Logs channel removed",
        
        # General Commands
        'general_title': "📋 General Commands",
        'general_description': "**General commands:**\n\n",
        'avatar': "Show your avatar",
        'server_icon': "Show server icon", 
        'user_info': "User information",
        'server_info': "Server information",
        'bot_count': "Bot count in server",
        'set_language': "Change bot language",
        
        # Admin Commands
        'admin_title': "⚙️ Admin Commands",
        'admin_description': "**Admin commands:**\n\n",
        'uptime_cmd': "Bot uptime",
        'mute_cmd': "Mute member",
        'unmute_cmd': "Unmute member",
        'kick_cmd': "Kick member",
        'ban_cmd': "Ban member",
        'unban_cmd': "Unban member",
        'setnick_cmd': "Change nickname",
        'moveall_cmd': "Move all to voice channel",
        'close_cmd': "Lock chat",
        'openchat_cmd': "Unlock chat",
        'create_text': "Create text channel",
        'create_voice': "Create voice channel",
        'clear_cmd': "Clear messages",
        'set_logs': "Set logs channel",
        'slowmode_cmd': "Set slowmode for channel",
        
        # Info Commands
        'info_title': "ℹ️ Bot Information",
        'info_description': "**Bot information:**\n\n",
        'bot_info': "Bot information",
        'invite_bot': "Bot invite",
        'developer_info': "Developer info",
        'contact_developer': "Contact Developer",
        'invite_bot_button': "Invite Bot",
        'ping': "Ping",
        'ping_response': "🏓 Pong! Latency: {latency}ms",
        
        # Responses
        'enabled': "Enabled",
        'disabled': "Disabled",
        'anti_bots_enabled': "✅ Anti-bots protection enabled",
        'anti_bots_disabled': "✅ Anti-bots protection disabled",
        'anti_bots_status': "🛡️ Anti-bots status: {status}",
        'invalid_setting': "❌ Invalid setting",
        'setting_updated': "✅ Set `{setting}` to `{value}`",
        
        # Logs
        'member_join': "🟢 {member} joined the server",
        'member_remove': "🔴 {member} left the server",
        'member_ban': "🔨 {moderator} banned {member}",
        'member_kick': "👢 {moderator} kicked {member}",
        'message_delete': "🗑️ Message deleted in {channel} by {author}",
        'channel_create': "📘 Channel created: {channel}",
        'channel_delete': "🗑️ Channel deleted: {channel}",
        'role_create': "🎨 Role created: {role}",
        'role_delete': "🗑️ Role deleted: {role}",
        
        # New admin tracking strings
        'admin_tracking': "Admin Tracking",
        'role_created_by': "Role created: {role_name} by {admin}",
        'role_deleted_by': "Role deleted: {role_name} by {admin}",
        'channel_created_by': "Channel created: {channel} by {admin}",
        'channel_deleted_by': "Channel deleted: {channel} by {admin}",
        'member_banned_by': "Member banned: {user} by {admin}",
        'member_kicked_by': "Member kicked: {user} by {admin}",
        'member_unbanned_by': "Member unbanned: {user} by {admin}",
        'nickname_changed_by': "Nickname changed: {user} by {admin}",
        'roles_updated_by': "Roles updated: {user} by {admin}",
        'messages_purged_by': "Messages purged: {count} messages by {admin}",
        'webhooks_updated_by': "Webhooks updated: {channel} by {admin}",
        
        # New strings for logs management
        'logs_management': "Log Channels Management",
        'logs_management_desc': "Use the buttons below to manage log channels:\n\n• **Add**: Add a new log channel by ID\n• **Remove**: Remove a log channel by ID\n• **View**: View current log channels",
        'add_log_channel': "Add Log Channel",
        'remove_log_channel': "Remove Log Channel", 
        'view_log_channels': "View Log Channels",
        'channel_added': "✅ Added {channel} to log channels",
        'channel_removed': "✅ Removed channel ID {channel_id} from log channels",
        'channel_exists': "❌ {channel} is already a log channel",
        'channel_not_found': "❌ Channel not found!",
        'invalid_channel_id': "❌ Invalid channel ID!",
        'no_log_channels': "❌ No log channels set.",
        'only_command_user': "⛔ Only the command user can change language!",
        
        # Settings Modal
        'settings_modal_title': "Change Protection Settings",
        'select_setting': "Setting Name (antibots, limitsban, etc)",
        'enter_value': "Value (true/false for antibots, number for limits)",
        'setting_antibots': "Anti-Bots Protection",
        'setting_limitsban': "Ban Limits",
        'setting_limitskick': "Kick Limits", 
        'setting_limitsroleC': "Role Create Limits",
        'setting_limitsroleD': "Role Delete Limits",
        'setting_limitschannelD': "Channel Delete Limits",
        
        # Slowmode
        'slowmode_set': "✅ Slowmode set to {seconds} seconds in {channel}",
        'slowmode_removed': "✅ Slowmode removed from {channel}",
        'slowmode_invalid': "❌ Slowmode must be between 0 and 21600 seconds (6 hours)",
        
        # Settings Guide
        'settings_guide': "**Available Settings:**\n• `antibots` - true/false (Enable anti-bots)\n• `limitsban` - number (Max bans)\n• `limitskick` - number (Max kicks)\n• `limitsroleC` - number (Max role creations)\n• `limitsroleD` - number (Max role deletions)\n• `limitschannelD` - number (Max channel deletions)",
        
        # New advanced strings
        'select_log_channels': "Select log channels...",
        'advanced_logs_title': "Advanced Log Channels Management",
        'advanced_protection_title': "Advanced Protection Settings",
        'select_setting_modify': "Select setting to modify...",
        
        # Advanced Logs Strings
        'advanced_logs_title': "🔧 Advanced Logs Management",
        'advanced_logs_desc': "**Customize logging events for each channel**\n\nSelect a channel to configure which events should be logged there.",
        'select_channel_configure': "Select channel to configure...",
        'log_settings_for': "Log Settings for {channel}",
        'log_settings_desc': "Toggle which events should be logged in this channel:",
        'log_event_member_join': "Member Join",
        'log_event_member_remove': "Member Leave", 
        'log_event_member_ban': "Member Ban",
        'log_event_member_kick': "Member Kick",
        'log_event_message_delete': "Message Delete",
        'log_event_channel_create': "Channel Create",
        'log_event_channel_delete': "Channel Delete",
        'log_event_role_create': "Role Create",
        'log_event_role_delete': "Role Delete",
        'log_event_message_edit': "Message Edit",
        'log_event_voice_join': "Voice Join",
        'log_event_voice_leave': "Voice Leave",
        'log_event_voice_move': "Voice Move",
        'log_event_channel_update': "Channel Update",
        'log_event_nickname_change': "Nickname Change",
        'log_event_role_update': "Role Update",
        'all_events': "All Events",
        'no_events': "No Events",
        'events_updated': "✅ Log events updated for {channel}",
        'enable_all': "Enable All",
        'disable_all': "Disable All",
        
        # Enhanced Command Strings
        'server_info_title': "🏰 Server Information",
        'user_info_title': "👤 User Information", 
        'developer_info_title': "👨‍💻 Developer Information",
        'members': "Members",
        'channels': "Channels",
        'roles': "Roles",
        'created': "Created",
        'joined': "Joined",
        'status': "Status",
        'activity': "Activity",
        'boosts': "Boosts",
        'verification': "Verification",
        'owner': "Owner",
        'bot_developer': "Bot Developer",
        'special_thanks': "Special Thanks",
        'support_server': "Support Server",
        'website': "Website",

        # ============ Music Strings ============
        'music_join': "Join your voice channel",
        'music_leave': "Leave the voice channel",
        'music_play': "Play a song or playlist from a URL or search",
        'music_skip': "Skip the current track",
        'music_pause': "Pause playback",
        'music_resume': "Resume playback",
        'music_stop': "Stop playback and clear the queue",
        'music_now': "Show the currently playing track",
        'music_queue': "Show the queue (now + upcoming)",
        'music_shuffle': "Shuffle the queue",
        'music_remove': "Remove an item from the queue",
        'music_loop': "Set loop mode: off/one/all",
        'music_volume': "Change volume (1-200)",
        'music_help': "Show music commands help",
        
        # Music Responses
        'MUST_BE_MEMBER': "This command requires a guild member.",
        'MUST_BE_IN_VOICE': "You must be connected to a voice channel.",
        'MUST_JOIN_BOT_CH': "Please join the voice channel the bot is in: **{channel}**.",
        'BOT_NOT_CONNECTED': "Bot is not connected. Join a voice channel then use /join or /play.",
        'ALREADY_HERE': "The bot is already connected in **{channel}**.",
        'JOINED': "Joined **{name}**.",
        'DISCONNECTED': "Disconnected from the voice channel ✌️",
        'ADDED_SINGLE_DETAIL': "Added: **{title}** • Source: **{source}**{query}",
        'ADDED_PLAYLIST_DETAIL': "Added **{count}** track(s) • Source: **{source}**{query}",
        'SKIPPED': "⏭️ Skipped.",
        'PAUSED': "⏸️ Paused.",
        'RESUMED': "▶️ Resumed.",
        'STOPPED': "⏹️ Stopped and cleared the queue.",
        'NOTHING_PLAYING': "Nothing is playing right now.",
        'NOW_TITLE': "Now Playing",
        'REQUESTED_BY': "Requested by",
        'SOURCE': "Source",
        'ORIGINAL_QUERY': "Original query",
        'DURATION': "Duration",
        'QUEUE_EMPTY': "The queue is empty 🎶",
        'QUEUE_TITLE': "Play Queue",
        'AND_MORE': "… and {more} more",
        'SHUFFLED': "🔀 Shuffled.",
        'REMOVED': "🗑️ Removed **{title}** from the queue.",
        'INVALID_INDEX': "Invalid index.",
        'LOOP_CHOOSE': "Choose: off | one | all",
        'LOOP_SET': "Loop mode set to: **{mode}**",
        'VOL_RANGE': "Value must be between 1 and 200.",
        'VOL_SET': "Volume set to **{level}%**",
        'LANG_SET_AR': "Language changed to Arabic.",
        'LANG_SET_EN': "Language changed to English.",
        'LANG_BAD': "Use: ar or en",
        'PRESENCE_SET': "Presence updated to **{state}** with text **{text}**.",
        'PRESENCE_NO_CHANGE': "No changes provided. Please specify state, activity_type or text.",
        'HELP_TITLE': "Bot Commands",
        'HELP_DESC': "Here is a list of available commands:",
        'MENTION': "Type /help to see the commands.",
        'NOT_AUTH': "❌ You are not authorized to use this command.",
        'NAME_UPDATED': "✅ Bot name updated to **{name}**.",
        'AVATAR_UPDATED': "✅ Bot avatar updated.",
        'BANNER_UPDATED': "✅ Bot banner updated.",
        'RATE_LIMIT': "You are doing this too fast. Please try again later.",
        'GENERIC_ERR': "Unexpected error: {err}",
        'URL_INVALID_YT': "Invalid YouTube URL. Use watch?v=ID, youtu.be/ID or playlist.",
        'URL_INVALID_SP': "Invalid Spotify URL. Only track/playlist are supported.",
        'URL_INVALID_SC': "Invalid SoundCloud URL. It must be a direct track URL.",
        'SC_HINT': "Hint: open the track page from the artist and copy that URL.",
        'FETCH_TIMEOUT': "Finding the source took longer than expected. Try again or provide a direct link.",
        'NO_PLAYABLE': "Could not find a playable version.",
        'DRM_UNSUPPORTED': "The source is DRM-protected and cannot be played.",
        'BOT_NO_CONNECT': "I lack **Connect** permission in this channel. Please grant Connect.",
        'BOT_NO_SPEAK': "I lack **Speak** permission in this channel. Please grant Speak.",
        'SYNC_DONE': "Commands have been synced for this server.",
        'SYNC_FAIL': "Failed to sync commands for this server.",
        
        # Music Categories
        'music_commands': 'Music Commands',
        'music_title': '🎵 Music Commands',
        'music_description': 'Commands for music playback:\n\n',
        'music_join': 'Join your voice channel',
        'music_leave': 'Leave the voice channel',
        'music_play': 'Play a song or playlist',
        'music_skip': 'Skip the current track',
        'music_pause': 'Pause playback',
        'music_resume': 'Resume playback',
        'music_stop': 'Stop playback and clear queue',
        'music_now': 'Show currently playing track',
        'music_queue': 'Show the queue',
        'music_shuffle': 'Shuffle the queue',
        'music_remove': 'Remove a track from queue',
        'music_loop': 'Set loop mode',
        'music_volume': 'Change volume (1-200)',
        
        # New Help Structure
        'help_structure': {
            'protection': "🛡️ Protection - Server security and moderation",
            'general': "📋 General - Everyday utility commands",
            'admin': "⚙️ Admin - Administrative tools (Admins only)",
            'info': "ℹ️ Information - Bot and developer info",
            'music': "🎵 Music - Music playback commands",
            'automod': "🛡️ AutoMod - Automatic moderation system",
            'owner': "👑 Owner - Bot owner commands",
            'logs': "📊 Logs - Logging management",
        }
    },
    'ar': {
        # General
        'not_admin': "⛔ هذا الأمر فقط لأدمن السيرفر!",
        'select_category': "اختر قسمًا...",
        'choose_language': "اختر لغتك:",
        
        # Stats
        'stats_status': "إحصائيات: {guilds} سيرفر | {users} عضو | وقت التشغيل: {uptime}",
        
        # Owner Commands
        'owner_only': "❌ هذا الأمر فقط لأصحاب البوت!",
        'presence_updated': "✅ تم تحديث حالة البوت",
        'status_updated': "✅ تم تحديث وضعية البوت",
        'presence_reset': "✅ تم إعادة تعيين حالة البوت إلى الافتراضي",
        'streaming_url_required': "❌ البث المباشر يتطلب رابط صالح (https://)",
        
        'activity_playing': "يلعب",
        'activity_streaming': "يبث",
        'activity_listening': "يستمع",
        'activity_watching': "يشاهد",
        'activity_competing': "يتنافس",
        
        'status_online': "متصل",
        'status_idle': "خامل",
        'status_dnd': "مشغول",
        'status_invisible': "مخفي",
        
        # AutoMod
        'automod_title': "🛡️ إعدادات الأوتو مود",
        'automod_description': "ضبط ميزات التعديل التلقائي",
        'automod_enabled': "الأوتو مود مفعل",
        'automod_disabled': "الأوتو مود معطل",
        'anti_spam': "مكافحة السبام",
        'anti_mention': "مكافحة المينشن",
        'anti_links': "مكافحة الروابط", 
        'bad_words': "فلترة الكلمات السيئة",
        'automod_updated': "✅ تم تحديث إعدادات الأوتو مود!",
        'automod_action': "🛡️ إجراء الأوتو مود",
        'spam_detection': "كشف السبام",
        'mass_mention': "مينشن جماعي",
        'link_posted': "رابط منشور",
        'bad_word': "كلمة سيئة",
        'automod_message_blocked': "🚫 تم حظر رسالتك بواسطة الأوتو مود",
        'automod_spam_blocked': "⚠️ توقف عن السبام من فضلك!",
        'automod_mentions_blocked': "⚠️ الكثير من المينشنز!",
        'automod_links_blocked': "⚠️ الروابط غير مسموحة!",
        'automod_words_blocked': "⚠️ تم اكتشاف لغة غير لائقة!",
        
        # Language
        'language_set': "✅ Bot language set to English.",
        'language_set_ar': "✅ تم تعيين اللغة للعربية.",
        'english': "الإنجليزية 🇺🇸",
        'arabic': "العربية 🇸🇦",
        
        # Help Menu
        'help_title': "🎯 قائمة الأوامر الرئيسية",
        'help_description': "**مرحبًا بك في قائمة المساعدة!**\n\nاختر قسمًا من القائمة المنسدلة أدناه لاستعراض الأوامر المتاحة.\n\n• **🛡️ الحماية** - أمان السيرفر والتعديل\n• **📋 العامة** - أوامر الاستخدام اليومي  \n• **⚙️ المسؤول** - أدوات الإدارة (للمسؤولين فقط)\n• **ℹ️ المعلومات** - معلومات البوت والمطور\n• **🎵 الموسيقى - قم بشراء النسخة المدفوعة لتستمتع بهذه الميزة",
        'protection_commands': "🛡️ أوامر الحماية",
        'general_commands': "📋 الأوامر العامة",
        'music_commands': "🎵 أوامر الموسيقى",
        'admin_commands': "⚙️ أوامر المسؤول",
        'info_commands': "ℹ️ معلومات",
        
        # Protection Commands
        'protection_title': "🛡️ أوامر الحماية",
        'protection_description': "**أوامر حماية السيرفر:**\n\n",
        'antibots_on': "تفعيل مانع البوتات",
        'antibots_off': "إيقاف مانع البوتات", 
        'settings_view': "عرض إعدادات الحماية",
        'current_settings': "الإعدادات الحالية للحماية",
        'available_settings': "الإعدادات المتاحة",
        'setting_usage': "الاستخدام: `/settings <setting> <value>`",
        'logs_set': "✅ تم تعيين قناة السجلات إلى {channel}",
        'logs_removed': "✅ تم إزالة قناة السجلات",
        
        # General Commands
        'general_title': "📋 الأوامر العامة",
        'general_description': "**أوامر عامة:**\n\n",
        'avatar': "عرض صورتك",
        'server_icon': "عرض صورة السيرفر",
        'user_info': "معلومات عنك",
        'server_info': "معلومات عن السيرفر",
        'bot_count': "عدد البوتات في السيرفر",
        'set_language': "تغيير لغة البوت",
        
        # Admin Commands
        'admin_title': "⚙️ أوامر المسؤول",
        'admin_description': "**أوامر المسؤولين:**\n\n",
        'uptime_cmd': "مدة تشغيل البوت",
        'mute_cmd': "كتم عضو",
        'unmute_cmd': "فك كتم عضو",
        'kick_cmd': "طرد عضو",
        'ban_cmd': "حظر عضو",
        'unban_cmd': "فك حظر عضو",
        'setnick_cmd': "تغيير اسم عضو",
        'moveall_cmd': "سحب الجميع للروم الصوتي",
        'close_cmd': "قفل الشات",
        'openchat_cmd': "فتح الشات",
        'create_text': "إنشاء روم كتابي",
        'create_voice': "إنشاء روم صوتي",
        'clear_cmd': "مسح الرسائل",
        'set_logs': "تعيين قناة السجلات",
        'slowmode_cmd': "تعيين وضع البطء للروم",
        
        # Owner Commands
        'owner_only': "❌ This command is for bot owners only!",
        'presence_updated': "✅ Bot presence has been updated",
        'status_updated': "✅ Bot status has been updated",
        'presence_reset': "✅ Bot presence has been reset to default",
        'streaming_url_required': "❌ Streaming activity requires a valid URL (https://)",
        
        'activity_playing': "Playing",
        'activity_streaming': "Streaming",
        'activity_listening': "Listening",
        'activity_watching': "Watching",
        'activity_competing': "Competing",
        
        'status_online': "Online",
        'status_idle': "Idle",
        'status_dnd': "Do Not Disturb",
        'status_invisible': "Invisible",
        
        # Info Commands
        'info_title': "ℹ️ معلومات البوت",
        'info_description': "**معلومات حول البوت:**\n\n",
        'bot_info': "معلومات عن البوت",
        'invite_bot': "دعوة البوت",
        'developer_info': "بروفايل المطور",
        'contact_developer': "تواصل مع المطور",
        'invite_bot_button': "دعوة البوت",
        'ping': "بينغ",
        'ping_response': "🏓 بونغ! سرعة الاستجابة: {latency}ms",
        
        # Responses
        'enabled': "مفعل",
        'disabled': "معطل",
        'anti_bots_enabled': "✅ تم تفعيل مانع البوتات",
        'anti_bots_disabled': "✅ تم إيقاف مانع البوتات",
        'anti_bots_status': "🛡️ وضعية مانع البوتات: {status}",
        'invalid_setting': "❌ إعداد غير صالح",
        'setting_updated': "✅ تم تعيين `{setting}` إلى `{value}`",
        
        # Logs
        'member_join': "🟢 {member} انضم إلى السيرفر",
        'member_remove': "🔴 {member} غادر السيرفر",
        'member_ban': "🔨 {moderator} حظر {member}",
        'member_kick': "👢 {moderator} طرد {member}",
        'message_delete': "🗑️ تم حذف رسالة في {channel} بواسطة {author}",
        'channel_create': "📘 تم إنشاء روم: {channel}",
        'channel_delete': "🗑️ تم حذف روم: {channel}",
        'role_create': "🎨 تم إنشاء رتبة: {role}",
        'role_delete': "🗑️ تم حذف رتبة: {role}",
        
        # New admin tracking strings
        'admin_tracking': "تتبع المسؤولين",
        'role_created_by': "تم إنشاء الرتبة: {role_name} بواسطة {admin}",
        'role_deleted_by': "تم حذف الرتبة: {role_name} بواسطة {admin}",
        'channel_created_by': "تم إنشاء الروم: {channel} بواسطة {admin}",
        'channel_deleted_by': "تم حذف الروم: {channel} بواسطة {admin}",
        'member_banned_by': "تم حظر العضو: {user} بواسطة {admin}",
        'member_kicked_by': "تم طرد العضو: {user} بواسطة {admin}",
        'member_unbanned_by': "تم فك حظر العضو: {user} بواسطة {admin}",
        'nickname_changed_by': "تم تغيير الاسم: {user} بواسطة {admin}",
        'roles_updated_by': "تم تحديث الرتب: {user} بواسطة {admin}",
        'messages_purged_by': "تم مسح الرسائل: {count} رسالة بواسطة {admin}",
        'webhooks_updated_by': "تم تحديث الويب هووك: {channel} بواسطة {admin}",
        
        # New strings for logs management
        'logs_management': "إدارة قنوات السجلات",
        'logs_management_desc': "استخدم الأزرار أدناه لإدارة قنوات السجلات:\n\n• **إضافة**: إضافة قناة سجلات جديدة\n• **إزالة**: إزالة قناة سجلات\n• **عرض**: عرض قنوات السجلات الحالية",
        'add_log_channel': "إضافة قناة سجلات",
        'remove_log_channel': "إزالة قناة سجلات",
        'view_log_channels': "عرض قنوات السجلات",
        'channel_added': "✅ تم إضافة {channel} إلى قنوات السجلات",
        'channel_removed': "✅ تم إزالة قناة {channel_id} من قنوات السجلات",
        'channel_exists': "❌ {channel} موجودة مسبقاً في قنوات السجلات",
        'channel_not_found': "❌ القناة غير موجودة!",
        'invalid_channel_id': "❌ رقم القناة غير صالح!",
        'no_log_channels': "❌ لا توجد قنوات سجلات مضافة.",
        'only_command_user': "⛔ فقط المستخدم الذي أمر بالتغيير يمكنه اختيار اللغة!",
        
        # Settings Modal
        'settings_modal_title': "تغيير إعدادات الحماية",
        'select_setting': "اسم الإعداد (antibots, limitsban, إلخ)",
        'enter_value': "القيمة (true/false لـ antibots, رقم للحدود)",
        'setting_antibots': "حماية ضد البوتات",
        'setting_limitsban': "حدود الحظر",
        'setting_limitskick': "حدود الطرد",
        'setting_limitsroleC': "حدود إنشاء الرتب",
        'setting_limitsroleD': "حدود حذف الرتب", 
        'setting_limitschannelD': "حدود حذف الرومات",
        
        # Slowmode
        'slowmode_set': "✅ تم تعيين وضع البطء إلى {seconds} ثانية في {channel}",
        'slowmode_removed': "✅ تم إزالة وضع البطء من {channel}",
        'slowmode_invalid': "❌ وضع البطء يجب أن يكون بين 0 و 21600 ثانية (6 ساعات)",
        
        # Settings Guide
        'settings_guide': "**الإعدادات المتاحة:**\n• `antibots` - true/false (تفعيل مانع البوتات)\n• `limitsban` - رقم (الحد الأقصى للحظر)\n• `limitskick` - رقم (الحد الأقصى للطرد)\n• `limitsroleC` - رقم (الحد الأقصى لإنشاء الرتب)\n• `limitsroleD` - رقم (الحد الأقصى لحذف الرتب)\n• `limitschannelD` - رقم (الحد الأقصى لحذف الرومات)",
        
        # New advanced strings
        'select_log_channels': "اختر قنوات السجلات...",
        'advanced_logs_title': "إدارة متقدمة لقنوات السجلات",
        'advanced_protection_title': "إعدادات حماية متقدمة", 
        'select_setting_modify': "اختر الإعداد للتعديل...",
        
        # Advanced Logs Strings
        'advanced_logs_title': "🔧 إدارة السجلات المتقدمة",
        'advanced_logs_desc': "**تخصيص أحداث السجلات لكل قناة**\n\nاختر قناة لضبط الأحداث التي يجب تسجيلها فيها.",
        'select_channel_configure': "اختر قناة للضبط...",
        'log_settings_for': "إعدادات السجلات لـ {channel}",
        'log_settings_desc': "حدد الأحداث التي يجب تسجيلها في هذه القناة:",
        'member_join': "انضمام عضو",
        'member_remove': "مغادرة عضو",
        'member_ban': "حظر عضو",
        'member_kick': "طرد عضو",
        'message_delete': "حذف رسالة",
        'channel_create': "إنشاء روم",
        'channel_delete': "حذف روم",
        'role_create': "إنشاء رتبة",
        'role_delete': "حذف رتبة",
        'message_edit': "تعديل رسالة",
        'voice_join': "دخول روم صوتي",
        'voice_leave': "خروج روم صوتي",
        'nickname_change': "تغيير اسم",
        'role_update': "تحديث رتبة",
        'all_events': "جميع الأحداث",
        'no_events': "لا أحداث",
        'events_updated': "✅ تم تحديث أحداث السجلات لـ {channel}",
        'enable_all': "تفعيل الكل",
        'disable_all': "تعطيل الكل",
        
        # Enhanced Command Strings
        'server_info_title': "🏰 معلومات السيرفر",
        'user_info_title': "👤 معلومات العضو", 
        'developer_info_title': "👨‍💻 معلومات المطور",
        'members': "الأعضاء",
        'channels': "الرومات",
        'roles': "الرتب",
        'created': "تاريخ الإنشاء",
        'joined': "تاريخ الانضمام",
        'status': "الحالة",
        'activity': "النشاط",
        'boosts': "البوستات",
        'verification': "المستوى",
        'owner': "المالك",
        'bot_developer': "مطور البوت",
        'special_thanks': "شكر خاص",
        'support_server': "سيرفر الدعم",
        'website': "الموقع الإلكتروني",

        # ============ Music Strings ============
        'music_join': "الانضمام إلى قناتك الصوتية",
        'music_leave': "مغادرة القناة الصوتية",
        'music_play': "تشغيل مقطع موسيقي أو قائمة من رابط أو بحث",
        'music_skip': "تخطي المقطع الحالي",
        'music_pause': "إيقاف التشغيل مؤقتاً",
        'music_resume': "استئناف التشغيل",
        'music_stop': "إيقاف التشغيل وتفريغ قائمة الانتظار",
        'music_now': "عرض المقطع المشغَّل حالياً",
        'music_queue': "عرض المقطوعات: الجاري + قائمة الانتظار",
        'music_shuffle': "إعادة ترتيب عشوائي لقائمة الانتظار",
        'music_remove': "حذف عنصر من قائمة الانتظار",
        'music_loop': "تحديد وضع التكرار: إيقاف/مقطع واحد/الكل",
        'music_volume': "تغيير مستوى الصوت (1-200)",
        'music_help': "عرض أوامر الموسيقى",
        
        # Music Responses
        'MUST_BE_MEMBER': "هذا الأمر يتطلب عضواً في الخادم.",
        'MUST_BE_IN_VOICE': "ينبغي أن تكون متصلاً بقناة صوتية.",
        'MUST_JOIN_BOT_CH': "الرجاء الانضمام إلى القناة الصوتية التي يوجد فيها البوت: **{channel}**.",
        'BOT_NOT_CONNECTED': "البوت غير متصل. ادخل قناة صوتية ثم استخدم /join أو /play.",
        'ALREADY_HERE': "البوت متصل بالفعل في **{channel}**.",
        'JOINED': "تم الانضمام إلى **{name}**.",
        'DISCONNECTED': "تمت مغادرة القناة الصوتية ✌️",
        'ADDED_SINGLE_DETAIL': "تمت إضافة: **{title}** • المصدر: **{source}**{query}",
        'ADDED_PLAYLIST_DETAIL': "تمت إضافة **{count}** مقطوعات • المصدر: **{source}**{query}",
        'SKIPPED': "تم التخطي.",
        'PAUSED': "تم الإيقاف المؤقت.",
        'RESUMED': "تم الاستئناف.",
        'STOPPED': "تم إيقاف التشغيل وتفريغ قائمة الانتظار.",
        'NOTHING_PLAYING': "لا يوجد تشغيل حالياً.",
        'NOW_TITLE': "يُشغَّل الآن",
        'REQUESTED_BY': "بطلب من",
        'SOURCE': "المصدر",
        'ORIGINAL_QUERY': "نص البحث",
        'DURATION': "المدة",
        'QUEUE_EMPTY': "قائمة الانتظار فارغة 🎶",
        'QUEUE_TITLE': "قائمة الانتظار",
        'AND_MORE': "… و {more} أخرى",
        'SHUFFLED': "تمت إعادة الترتيب عشوائياً.",
        'REMOVED': "تم حذف **{title}** من قائمة الانتظار.",
        'INVALID_INDEX': "الرقم غير صالح.",
        'LOOP_CHOOSE': "اختر: off | one | all",
        'LOOP_SET': "تم ضبط وضع التكرار على: **{mode}**",
        'VOL_RANGE': "ينبغي أن تكون القيمة بين 1 و200.",
        'VOL_SET': "تم ضبط مستوى الصوت: **{level}%**",
        'LANG_SET_AR': "تم تعيين اللغة إلى العربية.",
        'LANG_SET_EN': "تم تعيين اللغة إلى الإنجليزية.",
        'LANG_BAD': "استخدم: ar أو en",
        'PRESENCE_SET': "تم تحديث الحالة إلى **{state}** مع النص **{text}**.",
        'PRESENCE_NO_CHANGE': "لم تُحدِّد أي تغيير. رجاءً حدّد الحالة أو نوع النشاط أو النص.",
        'HELP_TITLE': "أوامر البوت",
        'HELP_DESC': "فيما يلي قائمة الأوامر المتاحة:",
        'MENTION': "اكتب /help لعرض الأوامر.",
        'NOT_AUTH': "❌ غير مخوّل باستخدام هذا الأمر.",
        'NAME_UPDATED': "✅ تم تحديث اسم البوت إلى **{name}**.",
        'AVATAR_UPDATED': "✅ تم تحديث صورة البوت.",
        'BANNER_UPDATED': "✅ تم تحديث بانر البوت.",
        'RATE_LIMIT': "تم تنفيذ الطلب بسرعة كبيرة. يرجى المحاولة لاحقاً.",
        'GENERIC_ERR': "حدث خطأ غير متوقع: {err}",
        'URL_INVALID_YT': "رابط يوتيوب غير صالح. استخدم watch?v=ID أو youtu.be/ID أو playlist.",
        'URL_INVALID_SP': "رابط سبوتيفاي غير صالح. المسار/القائمة فقط.",
        'URL_INVALID_SC': "رابط ساوندكلاود غير صالح. يجب أن يكون رابط مسار مباشر.",
        'SC_HINT': "تلميح: افتح صفحة المسار من حساب الفنان ثم انسخ الرابط المباشر.",
        'FETCH_TIMEOUT': "استغرق العثور على المصدر وقتاً أطول من المتوقع. جرّب ثانية أو أعطِ رابطاً مباشراً.",
        'NO_PLAYABLE': "تعذّر العثور على نسخة قابلة للتشغيل.",
        'DRM_UNSUPPORTED': "المصدر محمي بنظام DRM ولا يمكن تشغيله.",
        'BOT_NO_CONNECT': "لا أملك صلاحية **الاتصال (Connect)** في هذه القناة. أعطني Connect.",
        'BOT_NO_SPEAK': "لا أملك صلاحية **التحدّث (Speak)** في هذه القناة. أعطني Speak.",
        'SYNC_DONE': "تمت مزامنة الأوامر لهذا الخادم.",
        'SYNC_FAIL': "تعذّرت مزامنة الأوامر لهذا الخادم.",
        
        # Music Categories
        'music_commands': 'أوامر الموسيقى',
        'music_title': '🎵 أوامر الموسيقى',
        'music_description': 'أوامر تشغيل الموسيقى:\n\n',
        'music_join': 'الانضمام إلى قناتك الصوتية',
        'music_leave': 'مغادرة القناة الصوتية',
        'music_play': 'تشغيل مقطع أو قائمة تشغيل',
        'music_skip': 'تخطي المقطع الحالي',
        'music_pause': 'إيقاف التشغيل مؤقتاً',
        'music_resume': 'استئناف التشغيل',
        'music_stop': 'إيقاف التشغيل وتفريغ قائمة الانتظار',
        'music_now': 'عرض المقطع المشغّل حالياً',
        'music_queue': 'عرض قائمة الانتظار',
        'music_shuffle': 'إعادة ترتيب قائمة الانتظار',
        'music_remove': 'إزالة مقطع من قائمة الانتظار',
        'music_loop': 'ضبط وضع التكرار',
        'music_volume': 'تغيير مستوى الصوت (1-200)',
        
        # New Help Structure
        'help_structure': {
            'protection': "🛡️ الحماية - أمان السيرفر والتعديل",
            'general': "📋 العامة - أوامر الاستخدام اليومي",
            'admin': "⚙️ المسؤول - أدوات الإدارة (للمسؤولين فقط)",
            'info': "ℹ️ المعلومات - معلومات البوت والمطور",
            'music': "🎵 الموسيقى - أوامر تشغيل الموسيقى",
            'automod': "🛡️ الأوتو مود - نظام التعديل التلقائي",
            'owner': "👑 المالك - أوامر مالك البوت",
            'logs': "📊 السجلات - إدارة السجلات",
        }
    }
}
